# Generated by Django 5.1.5 on 2025-01-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
